-- ============================================================
-- Lumina Ops Hub — Row Level Security Policies
-- Run AFTER schema.sql
-- ============================================================

-- Enable RLS on all tables
ALTER TABLE mt5_accounts       ENABLE ROW LEVEL SECURITY;
ALTER TABLE mt5_trades         ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_jobs           ENABLE ROW LEVEL SECURITY;
ALTER TABLE auto_tasks         ENABLE ROW LEVEL SECURITY;
ALTER TABLE poly_markets       ENABLE ROW LEVEL SECURITY;
ALTER TABLE poly_positions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE arbitrage_signals  ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax_entries        ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax_pot            ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads              ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_briefings    ENABLE ROW LEVEL SECURITY;
ALTER TABLE allocation_rules   ENABLE ROW LEVEL SECURITY;
ALTER TABLE synergy_links      ENABLE ROW LEVEL SECURITY;
ALTER TABLE montecarlo_results ENABLE ROW LEVEL SECURITY;

-- ─── Helper: current user id ──────────────────────────────────────────────────
-- auth.uid() is built-in to Supabase, no need to define

-- ─── MT5 Accounts ────────────────────────────────────────────────────────────
CREATE POLICY "mt5_accounts_owner"   ON mt5_accounts   FOR ALL USING (user_id = auth.uid());

-- ─── MT5 Trades ───────────────────────────────────────────────────────────────
CREATE POLICY "mt5_trades_owner"     ON mt5_trades     FOR ALL USING (user_id = auth.uid());

-- ─── Ops Jobs ─────────────────────────────────────────────────────────────────
CREATE POLICY "ops_jobs_owner"       ON ops_jobs       FOR ALL USING (user_id = auth.uid());

-- ─── Auto Tasks ───────────────────────────────────────────────────────────────
CREATE POLICY "auto_tasks_owner"     ON auto_tasks     FOR ALL USING (user_id = auth.uid());

-- ─── Poly Markets (public read, no user restriction) ─────────────────────────
CREATE POLICY "poly_markets_public_read" ON poly_markets FOR SELECT USING (true);
-- Only service role can write market data (via Edge Function)
CREATE POLICY "poly_markets_service_write" ON poly_markets FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "poly_markets_service_update" ON poly_markets FOR UPDATE USING (auth.role() = 'service_role');

-- ─── Poly Positions ───────────────────────────────────────────────────────────
CREATE POLICY "poly_positions_owner" ON poly_positions FOR ALL USING (user_id = auth.uid());

-- ─── Arbitrage Signals ────────────────────────────────────────────────────────
CREATE POLICY "arb_signals_owner"    ON arbitrage_signals FOR ALL USING (user_id = auth.uid());
-- Allow service role (Edge Function) to insert signals for any user
CREATE POLICY "arb_signals_service"  ON arbitrage_signals FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- ─── Tax Entries ──────────────────────────────────────────────────────────────
CREATE POLICY "tax_entries_owner"    ON tax_entries    FOR ALL USING (user_id = auth.uid());

-- ─── Tax Pot ──────────────────────────────────────────────────────────────────
CREATE POLICY "tax_pot_owner"        ON tax_pot        FOR ALL USING (user_id = auth.uid());

-- ─── Leads ────────────────────────────────────────────────────────────────────
CREATE POLICY "leads_owner"          ON leads          FOR ALL USING (user_id = auth.uid());

-- ─── Daily Briefings ──────────────────────────────────────────────────────────
CREATE POLICY "briefings_owner"      ON daily_briefings FOR ALL USING (user_id = auth.uid());
-- Service role can insert briefings (generated by nightly Edge Function)
CREATE POLICY "briefings_service"    ON daily_briefings FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- ─── Allocation Rules ─────────────────────────────────────────────────────────
CREATE POLICY "alloc_rules_owner"    ON allocation_rules FOR ALL USING (user_id = auth.uid());
CREATE POLICY "alloc_rules_service"  ON allocation_rules FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "alloc_rules_service_update" ON allocation_rules FOR UPDATE USING (auth.role() = 'service_role');

-- ─── Synergy Links ────────────────────────────────────────────────────────────
CREATE POLICY "synergy_owner"        ON synergy_links   FOR ALL USING (user_id = auth.uid());

-- ─── Monte Carlo Results ──────────────────────────────────────────────────────
CREATE POLICY "mc_owner"             ON montecarlo_results FOR ALL USING (user_id = auth.uid());
CREATE POLICY "mc_service"           ON montecarlo_results FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- ─── Realtime publication ─────────────────────────────────────────────────────
-- Allow realtime on key tables so useRealtime.ts subscriptions work:
ALTER PUBLICATION supabase_realtime ADD TABLE mt5_accounts;
ALTER PUBLICATION supabase_realtime ADD TABLE ops_jobs;
ALTER PUBLICATION supabase_realtime ADD TABLE arbitrage_signals;
ALTER PUBLICATION supabase_realtime ADD TABLE tax_pot;
ALTER PUBLICATION supabase_realtime ADD TABLE leads;
ALTER PUBLICATION supabase_realtime ADD TABLE daily_briefings;
